export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const LOG_OUT = "LOG_OUT";

///Product
export const PRODUCT_SERVER_START = "PRODUCT_SERVER_START";
export const PRODUCT_SERVER_ERROR = "PRODUCT_SERVER_ERROR";
//CREATE
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const MANAGE_PRODUCT = "MANAGE_PRODUCT";
export const MANAGE_PRODUCT_PRICE = "MANAGE_PRODUCT_PRICE";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
